Declarations and data importing

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/qlfs_2025_q4/qlfs-2025-q4-v1.csv")

In [3]:
df.head()

,UQNO,SURVEYDATE,PERSONNO,Q12NIGHTS,Q13GENDER,Q14DAY,Q14MONTH,Q14YEAR,Q14AGE,Q15POPULATION,...,Underempl,Hrswrk,Education_status,Neet,Graduates,Ste_icse93,Ste_icse18_authority,Ste_icse18,Ste_icse18_risk,Weight
0,160100880000001801,4112025,1,1,1,2,7,1996,29,4,...,2.0,45.0,6,2.0,3,1.0,4.0,8.0,5.0,3393.655742
1,160100880000001801,4112025,2,1,2,16,2,1998,27,4,...,2.0,35.0,6,2.0,4,1.0,4.0,8.0,5.0,3393.655742
2,160100880000001801,4112025,3,1,1,24,1,2024,1,4,...,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,3393.655742
3,160100880000005801,4112025,2,1,2,10,7,1977,48,4,...,2.0,40.0,5,2.0,2,1.0,4.0,8.0,5.0,1382.700384
4,160100880000005801,4112025,3,1,2,23,5,2016,9,4,...,NaN,NaN,2,NaN,1,NaN,NaN,NaN,NaN,1382.700384

In [4]:
df = df.rename(columns={'Q14GENDER': 'GENDER'})

In [5]:
df.head()

,UQNO,SURVEYDATE,PERSONNO,Q12NIGHTS,Q13GENDER,Q14DAY,Q14MONTH,Q14YEAR,Q14AGE,Q15POPULATION,...,Underempl,Hrswrk,Education_status,Neet,Graduates,Ste_icse93,Ste_icse18_authority,Ste_icse18,Ste_icse18_risk,Weight
0,160100880000001801,4112025,1,1,1,2,7,1996,29,4,...,2.0,45.0,6,2.0,3,1.0,4.0,8.0,5.0,3393.655742
1,160100880000001801,4112025,2,1,2,16,2,1998,27,4,...,2.0,35.0,6,2.0,4,1.0,4.0,8.0,5.0,3393.655742
2,160100880000001801,4112025,3,1,1,24,1,2024,1,4,...,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,3393.655742
3,160100880000005801,4112025,2,1,2,10,7,1977,48,4,...,2.0,40.0,5,2.0,2,1.0,4.0,8.0,5.0,1382.700384
4,160100880000005801,4112025,3,1,2,23,5,2016,9,4,...,NaN,NaN,2,NaN,1,NaN,NaN,NaN,NaN,1382.700384

In [7]:
df.columns

Index(['UQNO', 'SURVEYDATE', 'PERSONNO', 'Q12NIGHTS', 'Q13GENDER', 'Q14DAY',
       'Q14MONTH', 'Q14YEAR', 'Q14AGE', 'Q15POPULATION',
       ...
       'Underempl', 'Hrswrk', 'Education_status', 'Neet', 'Graduates',
       'Ste_icse93', 'Ste_icse18_authority', 'Ste_icse18', 'Ste_icse18_risk',
       'Weight'],
      dtype='object', length=200)